from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ASSUMPTIONS_PATH = ROOT / "data" / "assumptions.json"
OUTPUT_PATH = (
    ROOT
    / "docs"
    / "02_Investment_Financial_Strategy"
    / "Financial_Model_Output.md"
)


OFFSET_RATES = [0.70, 0.80, 0.90, 0.95]
PROJECT_COSTS = [60000, 70000, 80000, 100000]
OPPORTUNITY_COST_RATES = [0.05, 0.06, 0.07]


def aud(value: float) -> str:
    return f"${value:,.0f}"


def pct(value: float) -> str:
    return f"{value:.0%}"


def years(value: float) -> str:
    return f"{value:.1f} years"


def markdown_table(headers: list[str], rows: list[list[str]]) -> str:
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(row) + " |")
    return "\n".join(lines)


def annual_payment(principal: float, annual_rate: float, term_years: int) -> float:
    if annual_rate == 0:
        return principal / term_years
    return principal * annual_rate / (1 - (1 + annual_rate) ** -term_years)


def build_output() -> str:
    assumptions = json.loads(ASSUMPTIONS_PATH.read_text(encoding="utf-8"))
    annual_bill = assumptions["current_power_bill_annual"]
    default_offset_rate = assumptions["offset_rate_placeholder"]

    savings_rows = []
    annual_savings_by_offset = {}
    for offset in OFFSET_RATES:
        savings = annual_bill * offset
        annual_savings_by_offset[offset] = savings
        savings_rows.append([pct(offset), aud(savings), aud(annual_bill - savings)])

    payback_rows = []
    for cost in PROJECT_COSTS:
        row = [aud(cost)]
        for offset in OFFSET_RATES:
            row.append(years(cost / annual_savings_by_offset[offset]))
        payback_rows.append(row)

    opportunity_rows = []
    for cost in PROJECT_COSTS:
        row = [aud(cost)]
        for rate in OPPORTUNITY_COST_RATES:
            row.append(aud(cost * rate))
        opportunity_rows.append(row)

    finance_rate = default_offset_rate
    finance_term_years = 7
    finance_rows = []
    for cost in PROJECT_COSTS:
        yearly_payment = annual_payment(cost, finance_rate, finance_term_years)
        annual_savings_80 = annual_savings_by_offset[0.80]
        finance_rows.append(
            [
                aud(cost),
                aud(yearly_payment),
                aud(annual_savings_80),
                aud(annual_savings_80 - yearly_payment),
                f"{pct(finance_rate)} over {finance_term_years} years",
            ]
        )

    cash_vs_finance_rows = []
    for cost in PROJECT_COSTS:
        offset_cost = cost * default_offset_rate
        savings_80 = annual_savings_by_offset[0.80]
        yearly_payment = annual_payment(cost, finance_rate, finance_term_years)
        cash_vs_finance_rows.append(
            [
                aud(cost),
                aud(savings_80 - offset_cost),
                aud(savings_80 - yearly_payment),
                "Cash wins on annual cash flow"
                if savings_80 - offset_cost > savings_80 - yearly_payment
                else "Finance preserves cash but costs more annually",
            ]
        )

    return "\n\n".join(
        [
            "# Financial Model Output",
            "Generated by `tools/solar_financial_model.py`.",
            "## Baseline",
            markdown_table(
                ["Metric", "Value"],
                [
                    ["Current monthly power bill", aud(assumptions["current_power_bill_monthly"])],
                    ["Current annual power bill", aud(annual_bill)],
                    [
                        "Average daily consumption",
                        f'{assumptions["average_daily_consumption_kwh"]} kWh/day',
                    ],
                    ["Stage 1 solar", f'{assumptions["stage_1_solar_kw"]} kW'],
                    ["Stage 1 battery", f'{assumptions["stage_1_battery_kwh"]} kWh'],
                    ["Future solar design target", f'{assumptions["future_solar_kw"]} kW'],
                ],
            ),
            "## Annual Savings By Bill Offset",
            markdown_table(
                ["Bill offset", "Annual saving", "Residual annual bill"],
                savings_rows,
            ),
            "## Simple Payback",
            markdown_table(
                ["Project cost", "70% offset", "80% offset", "90% offset", "95% offset"],
                payback_rows,
            ),
            "## Offset Opportunity Cost",
            markdown_table(
                ["Cash used", "5% offset cost", "6% offset cost", "7% offset cost"],
                opportunity_rows,
            ),
            "## Financing Scenario",
            markdown_table(
                [
                    "Project cost",
                    "Annual finance payment",
                    "Annual saving at 80% offset",
                    "Net annual cash flow",
                    "Finance assumption",
                ],
                finance_rows,
            ),
            "## Cash Purchase Vs Financing",
            markdown_table(
                [
                    "Project cost",
                    "Cash net benefit after 6% offset cost",
                    "Finance net cash flow",
                    "Indicative reading",
                ],
                cash_vs_finance_rows,
            ),
            "## Notes",
            "- This is a simple first-pass model, not tax or financial advice.",
            "- Finance uses the offset rate placeholder as the assumed finance rate until real offers are collected.",
            "- The financing comparison uses an 80% bill offset as the base case.",
            "- NPV and IRR should be added after quotes, tax treatment, degradation, maintenance, and battery replacement assumptions are known.",
            "",
        ]
    )


def main() -> None:
    OUTPUT_PATH.write_text(build_output(), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()

